# Create beforehand with kubectl apply -f secret.yaml
# This secret would be created manually in the environment and would not reside in a (decoded) file in the repo
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  my_secret: "YTEyMzQK" # base64 representation of the secret ("a1234")