apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "config-tester-chart.fullname" . }}
data:
  application.conf: |-
{{ .Files.Get "config/application.conf" | indent 4}}
  global.conf: |-
{{ .Files.Get "config/global.conf" | indent 4 }}
